# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'email_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(800, 567)
        login_window.setStyleSheet("QMainWindow#MainWindow{\n"
"/background-color: qconicalgradient(cx:0.525, cy:0.534, angle:180.1, stop:0 rgba(109, 177, 193, 255), stop:0.9801 rgba(255, 192, 192, 255));/\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.153, x2:1, y2:0.00595455, stop:0 rgba(109, 177, 193, 255), stop:0.721393 rgba(255, 192, 192, 255));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_verticalLayout = QtWidgets.QVBoxLayout()
        self.main_verticalLayout.setObjectName("main_verticalLayout")
        self.login_email = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_email.sizePolicy().hasHeightForWidth())
        self.login_email.setSizePolicy(sizePolicy)
        self.login_email.setMaximumSize(QtCore.QSize(16777215, 50))
        self.login_email.setObjectName("login_email")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.login_email)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.login_email)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.enter_email = QtWidgets.QLineEdit(self.login_email)
        self.enter_email.setObjectName("enter_email")
        self.horizontalLayout_3.addWidget(self.enter_email)
        self.main_verticalLayout.addWidget(self.login_email)
        self.login_pw = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_pw.sizePolicy().hasHeightForWidth())
        self.login_pw.setSizePolicy(sizePolicy)
        self.login_pw.setMaximumSize(QtCore.QSize(16777215, 50))
        self.login_pw.setObjectName("login_pw")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.login_pw)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.login_pw)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.enter_pw = QtWidgets.QLineEdit(self.login_pw)
        self.enter_pw.setObjectName("enter_pw")
        self.horizontalLayout_4.addWidget(self.enter_pw)
        self.main_verticalLayout.addWidget(self.login_pw)
        self.ERROR = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ERROR.sizePolicy().hasHeightForWidth())
        self.ERROR.setSizePolicy(sizePolicy)
        self.ERROR.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ERROR.setObjectName("ERROR")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ERROR)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ERROR_message = QtWidgets.QLabel(self.ERROR)
        self.ERROR_message.setText("")
        self.ERROR_message.setAlignment(QtCore.Qt.AlignCenter)
        self.ERROR_message.setObjectName("ERROR_message")
        self.horizontalLayout_5.addWidget(self.ERROR_message)
        self.main_verticalLayout.addWidget(self.ERROR)
        self.buttons = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttons.sizePolicy().hasHeightForWidth())
        self.buttons.setSizePolicy(sizePolicy)
        self.buttons.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttons.setObjectName("buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Login_button = QtWidgets.QPushButton(self.buttons)
        self.Login_button.setObjectName("Login_button")
        self.horizontalLayout_2.addWidget(self.Login_button)
        self.main_verticalLayout.addWidget(self.buttons)
        self.horizontalLayout.addLayout(self.main_verticalLayout)
        login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_window)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "MainWindow"))
        self.label.setText(_translate("login_window", "EMAIL:         "))
        self.label_2.setText(_translate("login_window", "PASSWORD:"))
        self.Login_button.setText(_translate("login_window", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QMainWindow()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec_())
